#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-xbean
Version  : 3.4
Release  : 5
URL      : https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
Source0  : https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
Source1  : https://repo.gradle.org/gradle/libs-releases/org/apache/xbean/xbean/3.7/xbean-3.7.pom
Source2  : https://repo.maven.apache.org/maven2/org/apache/xbean/xbean/4.8/xbean-4.8.pom
Source3  : https://repo1.maven.org/maven2/org/apache/xbean/xbean-asm6-shaded/4.8/xbean-asm6-shaded-4.8.jar
Source4  : https://repo1.maven.org/maven2/org/apache/xbean/xbean-asm6-shaded/4.8/xbean-asm6-shaded-4.8.pom
Source5  : https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.pom
Source6  : https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.jar
Source7  : https://repo1.maven.org/maven2/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.pom
Source8  : https://repo1.maven.org/maven2/org/apache/xbean/xbean/3.4/xbean-3.4.pom
Source9  : https://repo1.maven.org/maven2/org/apache/xbean/xbean/3.7/xbean-3.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-xbean-data = %{version}-%{release}
Requires: mvn-xbean-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-xbean package.
Group: Data

%description data
data components for the mvn-xbean package.


%package license
Summary: license components for the mvn-xbean package.
Group: Default

%description license
license components for the mvn-xbean package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-xbean
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-xbean/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-xbean/NOTICE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean/3.7
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean/3.7/xbean-3.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean/4.8
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean/4.8/xbean-4.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-asm6-shaded/4.8
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-asm6-shaded/4.8/xbean-asm6-shaded-4.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-asm6-shaded/4.8
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-asm6-shaded/4.8/xbean-asm6-shaded-4.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.4
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.7
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.7
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean/3.4
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean/3.4/xbean-3.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean/3.7
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/xbean/xbean/3.7/xbean-3.7.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/xbean/xbean-asm6-shaded/4.8/xbean-asm6-shaded-4.8.jar
/usr/share/java/.m2/repository/org/apache/xbean/xbean-asm6-shaded/4.8/xbean-asm6-shaded-4.8.pom
/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.pom
/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.jar
/usr/share/java/.m2/repository/org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.pom
/usr/share/java/.m2/repository/org/apache/xbean/xbean/3.4/xbean-3.4.pom
/usr/share/java/.m2/repository/org/apache/xbean/xbean/3.7/xbean-3.7.pom
/usr/share/java/.m2/repository/org/apache/xbean/xbean/4.8/xbean-4.8.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-xbean/LICENSE
/usr/share/package-licenses/mvn-xbean/NOTICE
